# Generated by Django 5.0.3 on 2024-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0002_friendrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
