# Generated by Django 5.0.3 on 2024-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0004_alter_friendrequest_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialuser",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
