# Generated by Django 5.0.3 on 2024-04-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0005_socialuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
